function [methodinfo,structs,enuminfo,ThunkLibName]=nidaqmxprototype32(varargin)
%NIDAQMXPROTOTYPE32 Create structures to define interfaces found in 'NIDAQmx'.

%This function was generated by loadlibrary.m parser version  on Wed Feb 15 12:45:32 2017
%perl options:'NIDAQmx.i -outfile=nidaqmxprototype32.m'
ival={cell(1,0)}; % change 0 to the actual number of functions to preallocate the data.
structs=[];enuminfo=[];fcnNum=1;
fcns=struct('name',ival,'calltype',ival,'LHS',ival,'RHS',ival,'alias',ival);
ThunkLibName=[];
%% Task Control
% int32 __stdcall DAQmxSelfTestDevice ( const char deviceName []); 
fcns.name{fcnNum}='DAQmxSelfTestDevice'; fcns.calltype{fcnNum}='stdcall'; fcns.LHS{fcnNum}='long'; fcns.RHS{fcnNum}={'cstring'};fcnNum=fcnNum+1;
% int32 __stdcall DAQmxTaskControl ( TaskHandle taskHandle , int32 action ); 
fcns.name{fcnNum}='DAQmxTaskControl'; fcns.calltype{fcnNum}='stdcall'; fcns.LHS{fcnNum}='long'; fcns.RHS{fcnNum}={'voidPtr', 'long'};fcnNum=fcnNum+1;
% int32 __stdcall DAQmxResetDevice ( const char deviceName []); 
fcns.name{fcnNum}='DAQmxResetDevice'; fcns.calltype{fcnNum}='stdcall'; fcns.LHS{fcnNum}='long'; fcns.RHS{fcnNum}={'cstring'};fcnNum=fcnNum+1;
% int32 __stdcall DAQmxGetErrorString ( int32 errorCode , char errorString [], uInt32 bufferSize ); 
fcns.name{fcnNum}='DAQmxGetErrorString'; fcns.calltype{fcnNum}='stdcall'; fcns.LHS{fcnNum}='long'; fcns.RHS{fcnNum}={'long', 'cstring', 'ulong'};fcnNum=fcnNum+1;
% int32 __stdcall DAQmxGetExtendedErrorInfo ( char errorString [], uInt32 bufferSize ); 
fcns.name{fcnNum}='DAQmxGetExtendedErrorInfo'; fcns.calltype{fcnNum}='stdcall'; fcns.LHS{fcnNum}='long'; fcns.RHS{fcnNum}={'cstring', 'ulong'};fcnNum=fcnNum+1;
% int32 __stdcall DAQmxClearTask ( TaskHandle taskHandle ); 
fcns.name{fcnNum}='DAQmxClearTask'; fcns.calltype{fcnNum}='stdcall'; fcns.LHS{fcnNum}='long'; fcns.RHS{fcnNum}={'voidPtr'};fcnNum=fcnNum+1;
% int32 __stdcall DAQmxCreateTask ( const char taskName [], TaskHandle * taskHandle ); 
fcns.name{fcnNum}='DAQmxCreateTask'; fcns.calltype{fcnNum}='stdcall'; fcns.LHS{fcnNum}='long'; fcns.RHS{fcnNum}={'cstring', 'voidPtrPtr'};fcnNum=fcnNum+1;
% int32 __stdcall DAQmxStartTask ( TaskHandle taskHandle ); 
fcns.name{fcnNum}='DAQmxStartTask'; fcns.calltype{fcnNum}='stdcall'; fcns.LHS{fcnNum}='long'; fcns.RHS{fcnNum}={'voidPtr'};fcnNum=fcnNum+1;
% int32 __stdcall DAQmxStopTask ( TaskHandle taskHandle ); 
fcns.name{fcnNum}='DAQmxStopTask'; fcns.calltype{fcnNum}='stdcall'; fcns.LHS{fcnNum}='long'; fcns.RHS{fcnNum}={'voidPtr'};fcnNum=fcnNum+1;
% int32 __stdcall DAQmxClearTask ( TaskHandle taskHandle ); 
fcns.name{fcnNum}='DAQmxClearTask'; fcns.calltype{fcnNum}='stdcall'; fcns.LHS{fcnNum}='long'; fcns.RHS{fcnNum}={'voidPtr'};fcnNum=fcnNum+1;
% int32 __stdcall DAQmxWaitUntilTaskDone ( TaskHandle taskHandle , float64 timeToWait ); 
fcns.name{fcnNum}='DAQmxWaitUntilTaskDone'; fcns.calltype{fcnNum}='stdcall'; fcns.LHS{fcnNum}='long'; fcns.RHS{fcnNum}={'voidPtr', 'double'};fcnNum=fcnNum+1;
% int32 __stdcall DAQmxIsTaskDone ( TaskHandle taskHandle , bool32 * isTaskDone ); 
fcns.name{fcnNum}='DAQmxIsTaskDone'; fcns.calltype{fcnNum}='stdcall'; fcns.LHS{fcnNum}='long'; fcns.RHS{fcnNum}={'voidPtr', 'ulongPtr'};fcnNum=fcnNum+1;
% int32 __stdcall DAQmxGetSysTasks ( char * data , uInt32 bufferSize ); 
fcns.name{fcnNum}='DAQmxGetSysTasks'; fcns.calltype{fcnNum}='stdcall'; fcns.LHS{fcnNum}='long'; fcns.RHS{fcnNum}={'cstring', 'ulong'};fcnNum=fcnNum+1;
% int32 __stdcall DAQmxSetWriteRegenMode ( TaskHandle taskHandle , int32 data ); 
fcns.name{fcnNum}='DAQmxSetWriteRegenMode'; fcns.calltype{fcnNum}='Thunk'; fcns.LHS{fcnNum}='long'; fcns.RHS{fcnNum}={'voidPtr', 'long'};fcnNum=fcnNum+1;
% int32 __stdcall DAQmxSetWriteRelativeTo ( TaskHandle taskHandle , int32 data ); 
fcns.name{fcnNum}='DAQmxSetWriteRelativeTo'; fcns.calltype{fcnNum}='Thunk'; fcns.LHS{fcnNum}='long'; fcns.RHS{fcnNum}={'voidPtr', 'long'};fcnNum=fcnNum+1;
% int32 __stdcall DAQmxSetWriteOffset ( TaskHandle taskHandle , int32 data ); 
fcns.name{fcnNum}='DAQmxSetWriteOffset'; fcns.calltype{fcnNum}='Thunk'; fcns.LHS{fcnNum}='long'; fcns.RHS{fcnNum}={'voidPtr', 'long'};fcnNum=fcnNum+1;

%% Pin Write
% int32 __stdcall DAQmxCreateDOChan ( TaskHandle taskHandle , const char lines [], const char nameToAssignToLines [], int32 lineGrouping ); 
fcns.name{fcnNum}='DAQmxCreateDOChan'; fcns.calltype{fcnNum}='stdcall'; fcns.LHS{fcnNum}='long'; fcns.RHS{fcnNum}={'voidPtr', 'cstring', 'cstring', 'long'};fcnNum=fcnNum+1;
% int32 __stdcall DAQmxCreateDIChan ( TaskHandle taskHandle , const char lines [], const char nameToAssignToLines [], int32 lineGrouping ); 
fcns.name{fcnNum}='DAQmxCreateDIChan'; fcns.calltype{fcnNum}='stdcall'; fcns.LHS{fcnNum}='long'; fcns.RHS{fcnNum}={'voidPtr', 'cstring', 'cstring', 'long'};fcnNum=fcnNum+1;
% int32 __stdcall DAQmxWriteDigitalLines ( TaskHandle taskHandle , int32 numSampsPerChan , bool32 autoStart , float64 timeout , bool32 dataLayout , const uInt8 writeArray [], int32 * sampsPerChanWritten , bool32 * reserved ); 
fcns.name{fcnNum}='DAQmxWriteDigitalLines'; fcns.calltype{fcnNum}='stdcall'; fcns.LHS{fcnNum}='long'; fcns.RHS{fcnNum}={'voidPtr', 'long', 'ulong', 'double', 'ulong', 'uint8Ptr', 'longPtr', 'ulongPtr'};fcnNum=fcnNum+1;
% int32 __stdcall DAQmxCreateAOVoltageChan ( TaskHandle taskHandle , const char physicalChannel [], const char nameToAssignToChannel [], float64 minVal , float64 maxVal , int32 units , const char customScaleName []); 
fcns.name{fcnNum}='DAQmxCreateAOVoltageChan'; fcns.calltype{fcnNum}='stdcall'; fcns.LHS{fcnNum}='long'; fcns.RHS{fcnNum}={'voidPtr', 'cstring', 'cstring', 'double', 'double', 'long', 'cstring'};fcnNum=fcnNum+1;
% int32 __stdcall DAQmxWriteAnalogScalarF64 ( TaskHandle taskHandle , bool32 autoStart , float64 timeout , float64 value , bool32 * reserved ); 
fcns.name{fcnNum}='DAQmxWriteAnalogScalarF64'; fcns.calltype{fcnNum}='stdcall'; fcns.LHS{fcnNum}='long'; fcns.RHS{fcnNum}={'voidPtr', 'ulong', 'double', 'double', 'ulongPtr'};fcnNum=fcnNum+1;
% int32 __stdcall DAQmxWriteAnalogF64 ( TaskHandle taskHandle , int32 numSampsPerChan , bool32 autoStart , float64 timeout , bool32 dataLayout , const float64 writeArray [], int32 * sampsPerChanWritten , bool32 * reserved ); 
fcns.name{fcnNum}='DAQmxWriteAnalogF64'; fcns.calltype{fcnNum}='stdcall'; fcns.LHS{fcnNum}='long'; fcns.RHS{fcnNum}={'voidPtr', 'long', 'ulong', 'double', 'ulong', 'doublePtr', 'longPtr', 'ulongPtr'};fcnNum=fcnNum+1;
% int32 __stdcall DAQmxSetDOOutputDriveType ( TaskHandle taskHandle , const char channel [], int32 data ); 
fcns.name{fcnNum}='DAQmxSetDOOutputDriveType'; fcns.calltype{fcnNum}='stdcall'; fcns.LHS{fcnNum}='long'; fcns.RHS{fcnNum}={'voidPtr', 'cstring', 'long'};fcnNum=fcnNum+1;

%% Pin Read
% int32 __stdcall DAQmxCreateAIVoltageChan ( TaskHandle taskHandle , const char physicalChannel [], const char nameToAssignToChannel [], int32 terminalConfig , float64 minVal , float64 maxVal , int32 units , const char customScaleName []); 
fcns.name{fcnNum}='DAQmxCreateAIVoltageChan'; fcns.calltype{fcnNum}='stdcall'; fcns.LHS{fcnNum}='long'; fcns.RHS{fcnNum}={'voidPtr', 'cstring', 'cstring', 'long', 'double', 'double', 'long', 'cstring'};fcnNum=fcnNum+1;
% int32 __stdcall DAQmxReadAnalogScalarF64 ( TaskHandle taskHandle , float64 timeout , float64 * value , bool32 * reserved ); 
fcns.name{fcnNum}='DAQmxReadAnalogScalarF64'; fcns.calltype{fcnNum}='stdcall'; fcns.LHS{fcnNum}='long'; fcns.RHS{fcnNum}={'voidPtr', 'double', 'doublePtr', 'ulongPtr'};fcnNum=fcnNum+1;
% int32 __stdcall DAQmxReadAnalogF64 ( TaskHandle taskHandle , int32 numSampsPerChan , float64 timeout , bool32 fillMode , float64 readArray [], uInt32 arraySizeInSamps , int32 * sampsPerChanRead , bool32 * reserved ); 
fcns.name{fcnNum}='DAQmxReadAnalogF64'; fcns.calltype{fcnNum}='stdcall'; fcns.LHS{fcnNum}='long'; fcns.RHS{fcnNum}={'voidPtr', 'long', 'double', 'ulong', 'doublePtr', 'ulong', 'longPtr', 'ulongPtr'};fcnNum=fcnNum+1;
% int32 __stdcall DAQmxReadCounterScalarU32 ( TaskHandle taskHandle , float64 timeout , uInt32 * value , bool32 * reserved ); 
fcns.name{fcnNum}='DAQmxReadCounterScalarU32'; fcns.calltype{fcnNum}='stdcall'; fcns.LHS{fcnNum}='long'; fcns.RHS{fcnNum}={'voidPtr', 'double', 'ulongPtr', 'ulongPtr'};fcnNum=fcnNum+1;
% int32 __stdcall DAQmxGetReadAvailSampPerChan ( TaskHandle taskHandle , uInt32 * data ); 
fcns.name{fcnNum}='DAQmxGetReadAvailSampPerChan'; fcns.calltype{fcnNum}='stdcall'; fcns.LHS{fcnNum}='long'; fcns.RHS{fcnNum}={'voidPtr', 'ulongPtr'};fcnNum=fcnNum+1;
% int32 __stdcall DAQmxReadCounterU32 ( TaskHandle taskHandle , int32 numSampsPerChan , float64 timeout , uInt32 readArray [], uInt32 arraySizeInSamps , int32 * sampsPerChanRead , bool32 * reserved ); 
fcns.name{fcnNum}='DAQmxReadCounterU32'; fcns.calltype{fcnNum}='stdcall'; fcns.LHS{fcnNum}='long'; fcns.RHS{fcnNum}={'voidPtr', 'long', 'double', 'ulongPtr', 'ulong', 'longPtr', 'ulongPtr'};fcnNum=fcnNum+1;

%% Clock/Counter
% int32 __stdcall DAQmxCfgSampClkTiming ( TaskHandle taskHandle , const char source [], float64 rate , int32 activeEdge , int32 sampleMode , uInt64 sampsPerChan ); 
fcns.name{fcnNum}='DAQmxCfgSampClkTiming'; fcns.calltype{fcnNum}='stdcall'; fcns.LHS{fcnNum}='long'; fcns.RHS{fcnNum}={'voidPtr', 'cstring', 'double', 'long', 'long', 'uint64'};fcnNum=fcnNum+1;
% int32 __stdcall DAQmxCreateCOPulseChanFreq ( TaskHandle taskHandle , const char counter [], const char nameToAssignToChannel [], int32 units , int32 idleState , float64 initialDelay , float64 freq , float64 dutyCycle ); 
fcns.name{fcnNum}='DAQmxCreateCOPulseChanFreq'; fcns.calltype{fcnNum}='stdcall'; fcns.LHS{fcnNum}='long'; fcns.RHS{fcnNum}={'voidPtr', 'cstring', 'cstring', 'long', 'long', 'double', 'double', 'double'};fcnNum=fcnNum+1;
% int32 __stdcall DAQmxCfgImplicitTiming ( TaskHandle taskHandle , int32 sampleMode , uInt64 sampsPerChan ); 
fcns.name{fcnNum}='DAQmxCfgImplicitTiming'; fcns.calltype{fcnNum}='stdcall'; fcns.LHS{fcnNum}='long'; fcns.RHS{fcnNum}={'voidPtr', 'long', 'uint64'};fcnNum=fcnNum+1;
% int32 __stdcall DAQmxSetCOPulseTerm ( TaskHandle taskHandle , const char channel [], const char * data ); 
fcns.name{fcnNum}='DAQmxSetCOPulseTerm'; fcns.calltype{fcnNum}='stdcall'; fcns.LHS{fcnNum}='long'; fcns.RHS{fcnNum}={'voidPtr', 'cstring', 'cstring'};fcnNum=fcnNum+1;
% int32 __stdcall DAQmxCreateCICountEdgesChan ( TaskHandle taskHandle , const char counter [], const char nameToAssignToChannel [], int32 edge , uInt32 initialCount , int32 countDirection ); 
fcns.name{fcnNum}='DAQmxCreateCICountEdgesChan'; fcns.calltype{fcnNum}='stdcall'; fcns.LHS{fcnNum}='long'; fcns.RHS{fcnNum}={'voidPtr', 'cstring', 'cstring', 'long', 'ulong', 'long'};fcnNum=fcnNum+1;
% int32 __stdcall DAQmxSetCICountEdgesTerm ( TaskHandle taskHandle , const char channel [], const char * data ); 
fcns.name{fcnNum}='DAQmxSetCICountEdgesTerm'; fcns.calltype{fcnNum}='stdcall'; fcns.LHS{fcnNum}='long'; fcns.RHS{fcnNum}={'voidPtr', 'cstring', 'cstring'};fcnNum=fcnNum+1;
% int32 __stdcall DAQmxCreateCIPulseWidthChan ( TaskHandle taskHandle , const char counter [], const char nameToAssignToChannel [], float64 minVal , float64 maxVal , int32 units , int32 startingEdge , const char customScaleName []); 
fcns.name{fcnNum}='DAQmxCreateCIPulseWidthChan'; fcns.calltype{fcnNum}='stdcall'; fcns.LHS{fcnNum}='long'; fcns.RHS{fcnNum}={'voidPtr', 'cstring', 'cstring', 'double', 'double', 'long', 'long', 'cstring'};fcnNum=fcnNum+1;
% int32 __stdcall DAQmxSetCIPulseWidthTerm ( TaskHandle taskHandle , const char channel [], const char * data ); 
fcns.name{fcnNum}='DAQmxSetCIPulseWidthTerm'; fcns.calltype{fcnNum}='stdcall'; fcns.LHS{fcnNum}='long'; fcns.RHS{fcnNum}={'voidPtr', 'cstring', 'cstring'};fcnNum=fcnNum+1;
% int32 __stdcall DAQmxSetCICtrTimebaseSrc ( TaskHandle taskHandle , const char channel [], const char * data ); 
fcns.name{fcnNum}='DAQmxSetCICtrTimebaseSrc'; fcns.calltype{fcnNum}='stdcall'; fcns.LHS{fcnNum}='long'; fcns.RHS{fcnNum}={'voidPtr', 'cstring', 'cstring'};fcnNum=fcnNum+1;
% int32 __stdcall DAQmxSetCIDupCountPrevent ( TaskHandle taskHandle , const char channel [], bool32 data ); 
fcns.name{fcnNum}='DAQmxSetCIDupCountPrevent'; fcns.calltype{fcnNum}='stdcall'; fcns.LHS{fcnNum}='long'; fcns.RHS{fcnNum}={'voidPtr', 'cstring', 'ulong'};fcnNum=fcnNum+1;
% int32 __stdcall DAQmxCfgDigEdgeStartTrig ( TaskHandle taskHandle , const char triggerSource [], int32 triggerEdge ); 
fcns.name{fcnNum}='DAQmxCfgDigEdgeStartTrig'; fcns.calltype{fcnNum}='Thunk'; fcns.LHS{fcnNum}='long'; fcns.RHS{fcnNum}={'voidPtr', 'cstring', 'long'};fcnNum=fcnNum+1;

methodinfo=fcns;